In [18]:
import numpy as np
import pandas as pd
import lightgbm as lgb
from sklearn.metrics import mean_squared_error, mean_squared_log_error
from sklearn.preprocessing import StandardScaler, MinMaxScaler, MaxAbsScaler
from sklearn.model_selection import KFold
import matplotlib.pyplot as plt
from xgboost import XGBRegressor
from kaggle_util import *

In [2]:
res = pd.read_csv('../result/bayes.csv')

In [3]:
lag_leak = pd.read_csv('../result/non_fake_sub_lag_29.csv')

In [157]:
def fill_new_target(x):
    if not np.isnan(x['leak22']):
        return x['leak22']
    elif not np.isnan(x['leak6']):
        return x['leak6']
    elif not np.isnan(x['leak16']):
        return x['leak16']
    elif not np.isnan(x['leak']):
        return x['leak']
    else:
        return x['leak_all']

In [158]:
res['target'] = res.apply(fill_new_target, axis=1)

In [26]:
bayes = pd.read_csv('../result/scored_bayes_0.65.csv')

In [58]:
combine_bayes = pd.read_csv('../result/scored_leak_combin_0.65.csv')

In [59]:
res['combine'] = combine_bayes['target']

In [160]:
res[['ID','target']].to_csv('../result/combine_leaknew.csv', index=False)

In [142]:
res.loc[(res.leak6>0) & np.isnan(res.leak)].shape

(326, 7)

In [219]:
res.drop(['bayes', 'combine', 'leak6','leak22','leak16', 'leak_all'], axis=1, inplace=True)

In [223]:
res['kfold'] = pd.read_csv('../result/bayes_kfold_0.529.csv')['target']

In [181]:
leak6['clean'] = leak6_clean.compiled_leak

In [213]:
report = pd.read_csv('../input/report.csv', index_col = 'feature')

In [214]:
report.rmse.min()

0.7828340024753592

In [215]:
report.rmse.max()

0.8115260899884742

In [203]:
len(report.loc[report['rmse'] <= 0.642].index)

23

In [285]:
len(l)

NameError: name 'l' is not defined

In [204]:
train_clean = pd.read_csv('../input/train_clean.csv')

In [205]:
X = train_clean

In [211]:
cols = X[X > 0].count()[X[X > 0].count() > 200].sort_values().index

In [212]:
len(cols)

1088

In [208]:
X.shape

(4459, 4732)

In [232]:
bunk_leak = pd.read_csv('../input/bunk_leak.csv')

In [241]:
bunk_leak.drop('Unnamed: 0', axis = 1, inplace = True)

In [242]:
bunk_leak

,leak0,leak_best0,leak1,leak_best1,leak2,leak_best2,leak3,leak_best3,leak4,leak_best4,...,leak41,leak_best41,leak42,leak_best42,leak43,leak_best43,leak44,leak_best44,leak45,leak_best45
0,38000000.00,38000000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,600000.00,600000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200000.00,200000.00
2,NaN,NaN,NaN,NaN,7400000.00,7400000.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000000.00,2000000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000000.00,2000000.00
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2800000.00,2800000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,164000.00,164000.00,NaN,NaN,4000.00,4000.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,600000.00,600000.00,NaN,NaN,7192000.00,7192000.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,979000.00,979000.00,NaN,NaN,3333333.34,3333333.34,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,460000.00,460000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1100000.00,1100000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6200000.0,6200000.0,NaN,NaN
11,16000000.00,16000000.00,NaN,NaN,1000000.00,1000000.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180000.00,180000.00
12,354000.00,354000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,100000.0,100000.0,NaN,NaN
13,7000000.00,7000000.00,NaN,NaN,7192000.00,7192000.00,300000.0,300000.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,800000.00,800000.00,NaN,NaN,258000.00,258000.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,200000.00,200000.00,NaN,NaN,400000.00,400000.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1100000.0,1100000.0,NaN,NaN,NaN,NaN
17,3600000.00,3600000.00,NaN,NaN,1500000.00,1500000.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6000000.0,6000000.0,120000.00,120000.00
18,2786000.00,2786000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,858000.0,858000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,40000.00,40000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,200000.0,200000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1600000.00,1600000.00,NaN,NaN,NaN,NaN,3000000.0,3000000.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,3266666.66,3266666.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,10000000.0,10000000.0,NaN,NaN
22,6140000.00,6140000.00,NaN,NaN,21470000.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,400000.0,400000.0,NaN,NaN
23,14886000.00,14886000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5100000.0,5100000.0,7000000.00,7000000.00
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,400000.00,400000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200000.00,200000.00
26,6500000.00,6500000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1700000.00,1700000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,933333.34,933333.34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,600000.0,600000.0,1700000.0,1700000.0,NaN,NaN
29,4000000.00,4000000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,12000000.0,12000000.0,2670000.0,2670000.0,2000000.00,2000000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4429,1066666.66,1066666.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4430,NaN,NaN,NaN,NaN,24000000.00,24000000.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37600000.00,37600000.00
4431,20000000.00,20000000.00,NaN,NaN,NaN,NaN,1600000.0,1600000.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4432,20000000.00,20000000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4433,2200000.00,2200000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,100000.0,100000.0,20000000.0,20000000.0,3290000.00,3290000.00
4434,74000.00,74000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125000.00,125000.00
4435,800000.00,800000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4436,20000000.00,20000000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4437,5000000.00,5000000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5000000.00,5000000.00
4438,6000000.00,6000000.00,21000000.0,21000000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4439,4666666.66,4666666.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4000000.00,4000000.00
4440,60000.00,60000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4442,2000000.00,2000000.00,NaN,NaN,600000.00,600000.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4443,528666.66,528666.66,378000.0,378000.0,370000.00,NaN,879000.0,879000.0,3192666.66,3192666.66,...,328000.0,328000.0,640000.0,640000.0,145600.0,145600.0,1000000.0,1000000.0,4000000.00,4000000.00
4444,300000.00,300000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4445,1000000.00,1000000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4446,10000000.00,10000000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,10000000.0,10000000.0,NaN,NaN
4447,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4448,3250000.00,3250000.00,NaN,NaN,4000000.00,4000000.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5333333.34,5333333.34
4449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,180000.0,180000.0,NaN,NaN
4450,21700000.00,21700000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4451,21320000.00,21320000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4453,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4454,1065000.00,1065000.00,NaN,NaN,2700000.00,2700000.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4455,48000.00,48000.00,NaN,NaN,48000.00,48000.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4456,2800000.00,2800000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,200000.0,200000.0,NaN,NaN
4457,10000000.00,10000000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4458,20000000.00,20000000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [278]:
(bunk_leak > 0).sum().sort_values(ascending = False)

leak0          3666
leak_best0     3663
leak16         1557
leak_best16    1548
leak17         1349
leak_best17    1335
leak30         1029
leak_best30    1025
leak13          942
leak_best13     937
leak2           881
leak45          851
leak_best2      847
leak_best45     840
leak44          731
leak_best44     728
leak12          691
leak_best12     680
leak6           624
leak8           622
leak_best6      616
leak_best8      616
leak34          582
leak_best34     581
leak33          529
leak_best33     521
leak43          489
leak_best43     478
leak9           442
leak_best9      440
               ...
leak39          170
leak_best39     168
leak20          155
leak_best20     154
leak42          151
leak_best42     147
leak41          144
leak_best41     142
leak23          138
leak_best23     136
leak40          135
leak_best40     134
leak3           131
leak37          131
leak_best3      130
leak_best37     130
leak32          122
leak_best32     121
leak35          110
leak_best35     109
leak18          101
leak22          101
leak_best22     100
leak10           97
leak_best10      96
leak_best18      94
leak36           70
leak_best36      66
leak38           60
leak_best38      58
Length: 92, dtype: int64

In [252]:
sort_leak = bunk_leak[cols]

In [260]:
sort_leak.to_csv('../input/sort_leak_all.csv', index=False)

In [267]:
leak_cols = ['leak{}'.format(i) for i in range(39)]

In [271]:
stack = sort_leak[leak_cols].bfill(1).iloc[:,0]

In [274]:
df_stack = pd.DataFrame({'compiled_leak': stack})

In [361]:
for idx, cols in enumerate(ext):
    if '64e483341' in cols:
        print(idx, cols)

6 ['64e483341', 'a75d400b8', '4fe8154c8', '29ab304b9', '20604ed8f', 'bd8f989f1', 'c1b9f4e76', '4824c1e90', '4ead853dc', 'b599b0064', 'd26279f1a', '58ed8fb53', 'ff65215db', '402bb0761', '74d7998d4', 'c7775aabf', '9884166a7', 'beb7f98fd', 'fd99c18b5', 'd83a2b684', '18c35d2ea', '0c8063d63', '400e9303d', 'c976a87ad', '8a088af55', '5f341a818', '5dca793da', 'db147ffca', '762cbd0ab', 'fb5a3097e', '8c0a1fa32', '01005e5de', '47cd6e6e4', 'f58fb412c', 'a1db86e3b', '50e4f96cf', 'f514fdb2e', '7a7da3079', 'bb1113dbb']
12 ['1d9078f84', '64e483341', 'a75d400b8', '4fe8154c8', '29ab304b9', '20604ed8f', 'bd8f989f1', 'c1b9f4e76', '4824c1e90', '4ead853dc', 'b599b0064', 'd26279f1a', '58ed8fb53', 'ff65215db', '402bb0761', '74d7998d4', 'c7775aabf', '9884166a7', 'beb7f98fd', 'fd99c18b5', 'd83a2b684', '18c35d2ea', '0c8063d63', '400e9303d', 'c976a87ad', '8a088af55', '5f341a818', '5dca793da', 'db147ffca', '762cbd0ab', 'fb5a3097e', '8c0a1fa32', '01005e5de', '47cd6e6e4', 'f58fb412c', 'a1db86e3b', '50e4f96cf', 'f514fdb2e', '7a7da3079', 'bb1113dbb']

In [313]:
def print_diff(lidx, extidx):
    coll = l[lidx]
    colext = ext[extidx]
    for idx, col in enumerate(coll):
        if coll[idx] != colext[idx]:
            print(idx, coll[idx], colext[idx])

In [360]:
print_diff(5,6)

In [308]:
for cols in l:
    print(cols)

['9df4daa99', '83c3779bf', 'edc84139a', 'f1e0ada11', '73687e512', 'aa164b93b', '342e7eb03', 'cd24eae8a', '8f3740670', '2b2a10857', 'a00adf70e', '3a48a2cd2', 'a396ceeb9', '9280f3d04', 'fec5eaf1a', '5b943716b', '22ed6dba3', '5547d6e11', 'e222309b0', '5d3b81ef8', '1184df5c2', '2288333b4', 'f39074b55', 'a8b721722', '13ee58af1', 'fb387ea33', '4da206d28', 'ea4046b8d', 'ef30f6be5', 'b85fa8b27', '2155f5e16', '794e93ca6', '070f95c99', '939f628a7', '7e814a30d', 'a6e871369', '0dc4d6c7d', 'bc70cbc26', 'aca228668']
['8e4d0fe45', '6c0e0801a', '02861e414', 'aac52d8d9', '041c5d0c9', 'd7875bb6c', 'e7c0cfd0f', 'd48c08bda', '0c9462c08', '57dd44c29', 'a93118262', '850027e38', 'db3839ab0', '27461b158', '32174174c', '9306da53f', '95742c2bf', '5831f4c76', '1e6306c7c', '06393096a', '13bdd610a', 'd7d314edc', '9a07d7b1f', '4d2671746', '822e49b95', '3c8a3ced0', '83635fb67', '1857fbccf', 'c4972742d', 'b6c0969a2', 'e78e3031b', '36a9a8479', 'e79e5f72c', '092271eb3', '74d7f2dc3', '277ef93fc', 'b30e932ba', '8f57141ec', '350473311']
['8c5025c23', 'f52a82e7f', 'c0b22b847', 'd75793f21', '4cffe31c7', '6c2d09fb1', 'fb42abc0d', '206ba1242', '62f61f246', '1389b944a', 'd15e80536', 'fa5044e9e', 'a0b0a7dbf', '1ff6be905', '4e06c5c6d', '1835531cd', '68b647452', 'c108dbb04', '58e8e2c82', 'f3bfa96d5', 'f2db09ac3', '4e8196700', '8cd9be80e', '83fc7f74c', 'dbc48d37c', '2028e022d', '17e160597', 'eb8cbd733', 'addb3f3eb', '460744630', '9108ee25c', 'b7950e538', 'a7da4f282', '7f0d863ba', 'b7492e4eb', '24c41bd80', 'fd7b0fc29', '621f71db3', '26f222d6d']
['b850c3e18', '212efda42', '9e7c6b515', '2d065b147', '49ca7ff2e', '37c85a274', 'ea5ed6ff7', 'deabe0f4c', 'bae4f747c', 'ca96df1db', '05b0f3e9a', 'eb19e8d63', '235b8beac', '85fe78c6c', 'cc507de6c', 'e0bb9cf0b', '80b14398e', '9ca0eee11', '4933f2e67', 'fe33df1c4', 'e03733f56', '1d00f511a', 'e62cdafcf', '3aad48cda', 'd36ded502', '92b13ebba', 'f30ee55dd', '1f8754c4e', 'db043a30f', 'e75cfcc64', '5d8a55e6d', '6e29e9500', 'c5aa7c575', 'c2cabb902', 'd251ee3b4', '73700eaa4', '8ab6f5695', '54b1c1bc0', 'cbd0256fb']
['18562fc62', '543c24e33', '0256b6714', 'd6006ff44', '6a323434b', 'e3a38370e', '7c444370b', '8d2d050a2', '9657e51e1', '13f3a3d19', 'b5c839236', '70f3033c6', 'f4b374613', '849125d91', '16b532cdc', '88219c257', '74fb8f14c', 'fd1102929', '699712087', '22501b58e', '9e9274b24', '2c42b0dce', '2c95e6e31', '5263c204d', '526ed2bec', '01f7de15d', 'cdbe394fb', 'adf357c9b', 'd0f65188c', 'b8a716ebf', 'ef1e1fac8', 'a3f2345bf', '110e4132e', '586b23138', '680159bab', 'f1a1562cd', '9f2f1099b', 'bf0e69e55', 'af91c41f0']
['64e483341', 'a75d400b8', '4fe8154c8', '29ab304b9', '20604ed8f', 'bd8f989f1', 'c1b9f4e76', '4824c1e90', '4ead853dc', 'b599b0064', 'd26279f1a', '58ed8fb53', 'ff65215db', '402bb0761', '74d7998d4', 'c7775aabf', '9884166a7', 'beb7f98fd', 'fd99c18b5', 'd83a2b684', '18c35d2ea', '0c8063d63', '400e9303d', 'c976a87ad', '8a088af55', '5f341a818', '5dca793da', 'db147ffca', '762cbd0ab', 'fb5a3097e', '8c0a1fa32', '01005e5de', '47cd6e6e4', 'f58fb412c', 'a1db86e3b', '50e4f96cf', 'f514fdb2e', '7a7da3079', 'bb1113dbb']

In [346]:
print(ext[6])

['64e483341', 'a75d400b8', '4fe8154c8', '29ab304b9', '20604ed8f', 'bd8f989f1', 'c1b9f4e76', '4824c1e90', '4ead853dc', 'b599b0064', 'd26279f1a', '58ed8fb53', 'ff65215db', '402bb0761', '74d7998d4', 'c7775aabf', '9884166a7', 'beb7f98fd', 'fd99c18b5', 'd83a2b684', '18c35d2ea', '0c8063d63', '400e9303d', 'c976a87ad', '8a088af55', '5f341a818', '5dca793da', 'db147ffca', '762cbd0ab', 'fb5a3097e', '8c0a1fa32', '47cd6e6e4', '01005e5de', 'f58fb412c', 'a1db86e3b', '50e4f96cf', 'f514fdb2e', '7a7da3079', 'bb1113dbb']

In [359]:
ext[6] = ['64e483341', 'a75d400b8', '4fe8154c8', '29ab304b9', '20604ed8f',
       'bd8f989f1', 'c1b9f4e76', '4824c1e90', '4ead853dc', 'b599b0064',
       'd26279f1a', '58ed8fb53', 'ff65215db', '402bb0761', '74d7998d4',
       'c7775aabf', '9884166a7', 'beb7f98fd', 'fd99c18b5', 'd83a2b684',
       '18c35d2ea', '0c8063d63', '400e9303d', 'c976a87ad', '8a088af55',
       '5f341a818', '5dca793da', 'db147ffca', '762cbd0ab', 'fb5a3097e',
       '8c0a1fa32', '01005e5de', '47cd6e6e4', 'f58fb412c', 'a1db86e3b',
       '50e4f96cf', 'f514fdb2e', '7a7da3079', 'bb1113dbb']

In [473]:
path = '../input/bunk_leak_test.csv'
df_leaks = pd.read_csv(path)

In [468]:
sort_cols = list((df_leaks > 0).sum().sort_values(ascending = False).index)

In [474]:
df_leaks[sort_cols].to_csv(path,index=False)

In [442]:
sort_cols_train = sort_cols.copy()

In [460]:
data = pd.read_csv('../input/train.csv')

In [461]:
data = pd.concat([data, df_leaks], axis=1, ignore_index=True)

In [475]:
df_leaks.head()

,leak0,leak15,leak16,leak12,leak28,leak2,leak43,leak11,leak6,leak42,...,leak22,leak33,leak19,leak21,leak17,leak3,leak9,leak30,leak34,leak36
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19524000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [458]:
df_leaks.shape

(4459, 1)

In [486]:
leak = pd.read_csv('../input/train_leak_tsne.csv')

In [479]:
transact_cols = [f for f in leak.columns if f not in ["ID", "target","compiled_leak"]]
leak['nonezero_mean'] = leak[transact_cols].apply(
            lambda x: np.expm1(np.log1p(x[x!=0]).mean()), axis=1
        )

In [483]:
bag = [i for i in range(10)]

In [484]:
options = [4,5,8]

In [485]:
[i for i in bag if i not in options]

[0, 1, 2, 3, 6, 7, 9]